In [3]:
########Thư viện numpy
#####Numpy cơ bản
import numpy as np
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

                                                 **Numpy Cơ bản**

In [4]:
[3.14,4,5,6,7]

[3.14, 4, 5, 6, 7]

In [5]:
np.array([1.45,2,3,4,5]) # khi có một hay nhiều phần tử thuộc float thì nó sẽ chuyển tất cả snag float

array([1.45, 2.  , 3.  , 4.  , 5.  ])

In [6]:
#cách chuyển dạng data từ interger thành float
np.array([1,2,3,4,5],dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [42]:
#chuyển float sang interger
a = np.array([1.1, 2.1, 3.1])

b = arr.astype('int64')

print(b)
print(b.dtype)

[1 2 3]
int64


In [18]:
#số dòng , số cột
a1=np.array([[[[1,2,3,4,5],
               [6,7,8,9,10],
               [1,2,3,4,5],
               [6,7,8,9,10]]]])
a1.shape

(1, 1, 4, 5)

In [32]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)


()
(5,)
(2, 3)
(2, 2, 3)


In [31]:

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [19]:
#số mảng
a1.ndim

4

In [20]:
#tông các thành phần
a1.size

20

In [ ]:
#Cách tạo numpy array từ các hàm có sẵn  zeros,ones,arange,full,linspace

In [22]:
#np.zeros([2,4]) #định dạng ban đầu là float
np.zeros([2,4],dtype=int)  #thay đổi định dạng

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
#Tạo mảng bắt từ từ 0 , kết thúc 20 và cách nhau 2 step
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
#mảng full theo số mình muốn 
np.full((3,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [30]:
from numpy.core.function_base import linspace
#tạo 1 array nằm trong khoảng từ 0 tới 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
#Cộng các phần tử trong mảng  , các mảng bắt đầu từ 0->n
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3]) #3+4=7

7


In [34]:
# lấy phần tử trong mảng
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4]) #dòng 2 cột 5

5th element on 2nd row:  10


In [35]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2]) # dòng 1 của mảng, dòng 2 , cột 3

6


In [36]:
#cắt mảng
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [37]:
#Cắt bước
#arr = np.array([1, 2, 3, 4, 5, 6, 7])
#print(arr[1:5:2])
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2]) ## cắt từ 0 đến n cắt nhau 2 step

[1 3 5 7]


In [38]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) #cắt dòng 2 , từ cột 2 tới cột 4

[7 8 9]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 2]) #cắt vị trí 1 đến 3 , ở vị trí 3 

In [43]:
## Định hình lại mảng
#1D thành 2D
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(4, 3)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [44]:
#1D thành 3D
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
b = a.reshape(2, 3 ,2)
print(b)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [46]:
#2D thành 1D
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(-1)
print(b)

[1 2 3 4 5 6]


In [47]:
#lặp lại mảng
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [48]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arr[:, ::2]): #lặp mảng từ 0 đến n và cách nhau 2 step
  print(x)

1
3
5
7


In [49]:
#Kết hợp mảng và tách mảng
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [50]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [51]:
#Chúng tôi chuyển một chuỗi các mảng mà chúng tôi muốn nối với stack()phương thức cùng với trục. Nếu trục không được thông qua một cách rõ ràng, nó được coi là 0.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [52]:
#NumPy cung cấp chức năng trợ giúp: hstack() xếp chồng dọc theo hàng.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [53]:
#NumPy cung cấp chức năng trợ giúp: vstack()  xếp chồng dọc theo cột.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [55]:
#NumPy cung cấp chức năng trợ giúp: dstack() xếp chồng dọc theo chiều cao, giống như chiều sâu.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [54]:
#Tách mảng
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [56]:
#chia thành mảng
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [57]:
#Tìm kiếm vị trí mảng 
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


In [59]:
#Sắp xếp mảng
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [60]:
#Lọc mảng , lấy các phần tử theo điều kiện
#Lấy các mảng lớn hơn 42
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [61]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


**Numpy Ngẫu nhiên**
